// les différents SONS à reconnaitre
sons["oi"]="a";	sons["oie"]="a";	sons["oigt"]="a";	sons["ah"]="a";		sons["a"]="a"; sons["oix"]="a"; sons["à"]="a";
sons["able"]="able";
sons["ache"]="ache";	sons["ash"]="ache";					
sons["ade"]="ade";						
sons["age"]="age";	sons["âge"]="age";					
sons["ail"]="ail";	sons["aille"]="ail";	sons["aïe"]="ail";				
sons["aiche"]="aiche"; sons["èche"]="aiche"; sons["êche"]="aiche";
sons["ain"]="ain";	sons["int"]="ain";	sons["inct"]="ain";	sons["ingt"]="ain";	sons["in"]="ain";	sons["ein"]="ain";	sons["ien"]="ain";
sons["aine"]="aine";	sons["en"]="aine";  sons["eine"]="aine"; sons["ène"]="aine";
sons["aire"]="aire";	sons["ère"]="aire";	sons["erf"]="aire";	 sons["air"] = "aire";		sons["ert"]="aire"; sons["super"]="aire"; sons["cutter"]="aire";
sons[" mer"]="aire";
sons["erre"]="aire";
sons["aise"]="aise";	sons["èse"]="aise";					
sons["al"]="al";	sons["ale"]="al";					
sons["ambe"]="ambe";						
sons["ambre"]="ambre";	sons["embre"]="ambre";					
sons["ame"]="ame";	sons["âme"]="ame"; sons["amme"]="ame";			
sons["ampe"]="ampe";	sons["empe"]="ampe";					
sons["an"]="an";	sons["ant"]="an";	sons["anc"]="an";	sons["and"]="an";	sons["ent"]="an";	sons["ang"]="an";	 sons["emps"]="an";
sons["arde"]="arde";
sons["angue"]="angue";
sons["auve"]="auve";
sons["patient"]="an";
sons[" client"] = "an";
sons["ance"]="ance";	sons["ence"]="ance";					
sons["anche"]="anche";	sons["enche"]="anche";					
sons["ande"]="ande";	sons["ende"]="ande";					
sons["ane"]="ane";	sons["anne"]="ane";					
sons["âne"]="âne";						
sons["ange"]="ange";	
sons["ante"]="ante"; sons["ente"]="ante";
sons["aphe"]="afe"; sons["afe"]="afe"; sons["af"]="afe"; sons["affe"]="afe";					
sons["apse"]="apse";						
sons["aque"]="aque";	sons["mac"]="aque";	sons["ouac"] = "aque";
sons["arbe"]="arbe";						
sons["are"]="are";	sons["ard"]="are";	sons["art"]="are";	sons["ar"]="are";			
sons["arpe"]="arpe";						
sons["ace"]="as";	sons["asse"]="as";	sons[" pancréas"]="as";	sons[" atlas"]="as";	sons["'atlas"]="as";	sons[" as"]="as";	
sons["asque"]="asque";						
sons["ate"]="ate";	sons["atte"]="ate";	
sons["ave"]="ave";
sons["aude"]="aude";							
sons["aume"]="aume";	sons["ome"]="aume";	sons["ôme"]="aume";				
sons["aune"]="aune"; sons[" iphone"] = "aune"; sons[" neurone"]="aune"; sons["ône"]="aune"; sons["gone"]="aune"; sons["chrone"]="aune";
sons["clone"]="aune"; sons["smartphone"]="aune";
sons["ôte"]="aute";	sons["aute"]="aute";					
sons["axe"]="ax";	sons["ax"]="ax";					
sons["er"]="é";	sons["é"]="é";	sons["ez"]="é";	sons["ée"]="é";	sons["ed"]="é";	sons["ai"]="é";	
sons[" ai"]="é"; sons[" aie"]="é"; sons[" aient"]="é"; sons["dvd"]="é"; sons["usb"]="é";
sons["è"]="è";	sons["et"]="è";	sons["ais"]="è";	sons["ait"]="è";	sons["aient"]="è";	sons["aid"]="è";	sons["êt"]="è";
sons["sydney"]="è";
sons["au"]="eau";	sons["eau"]="eau";	sons["eaux"]="eau";	sons["aux"]="eau";	sons["aulx"]="eau";	
sons["aud"]="eau"; sons["ault"]="eau";	
sons["èbre"]="èbre";						
sons["eil"]="eil";	sons["eille"]="eil";					
sons["elle"]="elle";	sons["aile"]="elle";	sons["el"]="elle";	sons["êle"]="elle";	 sons["ël"]="elle";
sons["ème"]="ème";	sons[" aime"]="ème";	sons["'aime"]="ème";	sons[" aiment"]="ème";	sons["'aiment"]="ème";	sons["em"]="ème";	
sons["entre"]="entre";	sons["antre"]="entre";					
sons["eps"]="eps";	sons["epps"]="eps";					
sons["èque"]="èque"; sons["êque"]="èque"; sons["ec"]="èque";
sons["erge"]="erge";						
sons["erme"]="erme";
sons["erte"]="erte";
sons["esse"]="esse";	sons["aisse"]="esse";		
sons[" mercedes"]="esse"; 
sons["ète"]="ète";	sons["ête"]="ète";					
sons["ètre"]="ètre";	sons["être"]="ètre";	sons["aître"]="ètre"; sons["aitre"]="ètre";				
sons["ette"]="ette";	sons["aite"]="ette";					
sons["euil"]="euil";	sons["euille"]="euil";					
sons["eul"]="eul";	sons["eule"]="eul";					
sons["eur"]="eur";	sons["eure"]="eur";	sons["œur"]="eur";				
sons["euse"]="euse";						
sons["eux"]="eux";	sons["eue"]="eux";					
sons["èvre"]="èvre";						
sons["ex"]="ex";	sons["exe"]="ex";					
sons["i"]="i";	sons["it"]="i";	sons["ie"]="i";	
sons["ri"]="i"; sons[" rie"]="i"; sons[" ries"]="i"; sons[" rient"]="i";
sons["iz"] = "i"; sons[" prix"]="i";
sons["ible"] = "ible";
sons["ice"]="ice";	sons[" clitoris"]="ice";	sons[" pubis"]="ice";	sons[" pénis"]="ice";	
sons[" pelvis"]="ice";	sons[" coccyx"]="ice";	sons[" son fils"]="ice";	sons[" mon fils"]="ice";	
sons[" ton fils"]="ice"; sons["tournevis"]="ice";
sons[" notre fils"]="ice";	sons[" leur fils"]="ice";	sons[" votre fils"]="ice";	sons[" un fils"]="ice";					

sons["iche"]="iche";					
sons["ide"]="ide";					
sons["if"]="if";	sons["iphe"]="if";				
sons["il"]="il";	sons["ile"]="il";				
sons["ille"]="ille";
sons["imbe"]="imbe";	sons["aimbe"]="imbe";				
sons["ime"]="ime";	sons["yme"]="ime";	sons["îme"]="ime";			
sons["ince"]="ince"; sons["reims"]="ince";
sons["ine"]="ine";	sons["inne"]="ine";				
sons["inge"]="inge";					
sons["inte"]="inte";
sons["inx"]="inx";	sons["ynx"]="inx";				
sons["ippe"] = "ip"; sons["ip"] = "ip"; sons["eep"]="ip";
sons["ir"] = "ire"; sons["ire"]="ire"; sons["irre"]="ire";
sons["ique"]="ique";	sons["ic"] = "ique";				
sons["ise"]="ise";	sons["yse"]="ise";				
sons["isque"]="isque";					
sons["iste"]="iste";					
sons["ite"]="ite";	sons["itte"]="ite";				
sons["ive"]="ive";	sons["yves"]="ive";				
sons["o"]="o";	sons["ot"]="o";	sons[" dos"]="o";	sons[" os"]="o";	sons[" abdo"]="o";	sons["croc"]="o";
sons["obe"]="obe";	sons["aube"]="obe";				
sons["oche"]="oche";
sons["ode"]	 ="ode"; 
sons["ogne"]="ogne";					
sons["oïde"]="oïde";					
sons["oile"]="oile";	sons["moelle"]="oile";	sons["oële"]="oile";	sons["oil"]="oile";		sons["oille"]="oile";
sons["oin"]="oin";	sons["oing"]="oin";	sons["oint"]="oin";	sons["ouin"]="oin";		
sons["oir"]="oir";	sons["oire"]="oir";				
sons["oitre"]="oitre"; sons["oître"]="oitre";
sons["ol"]="ol";	sons["ole"]="ol";	sons["olle"]="ol";	sons["aul"]="ol";	sons["aule"]="ol";	
sons["um"]="om";	sons["om"]="om";	sons["omme"]="om";			
sons["ompe"]="ompe";					
sons["on"]="on";	sons["ont"]="on";	sons["onc"]="on";	
sons["once"] = "once"; sons["onse"] = "once";		
sons["onche"]="onche";					
sons["onne"]="onne";	sons["lennon"]="onne";	sons["phone"]="onne"; sons["gorgone"]="onne"; sons["carbone"]="onne"; sons["one"]="onne"; sons["omne"]="onne";
sons["oque"]="oque"; sons["oc"]="oque"; sons["ock"]="oque";
sons["ore"]="ore";	sons["or"]="ore";	sons["orps"]="ore";		sons["aure"]="ore"; sons["ort"]="ore";
sons["orge"]="orge";					
sons["orse"]="orse";					
sons["orte"]="orte";	sons[" short"]="orte";
sons[" os"]="os";	sons["osse"]="os";	sons["oce"]="os";  sons["albatros"]="os";
sons["ose"]="ose";	sons["ause"]="ose";		
sons["otte"]="otte";	sons["ote"]	="otte";
sons["ou"]="ou";	sons["oue"]="ou";	sons["oux"]="ou"; sons["oo"]="ou";
sons["out"]="ou"; sons["oût"]="ou";			
sons["ouce"]="ouce";					
sons["ouche"]="ouche";					
sons["oude"]="oude";					
sons["ouf"]="ouf";	sons["ouffe"]="ouf";				
sons["ouge"]="ouge";
sons["ouïe"]="oui";	sons["oui"]="oui";	sons["huis"]="oui";		
sons["ouille"]="ouille";					
sons["oule"]="oul";	sons["oul"]="oul";				
sons["oune"]="oune";					
sons["oupe"]="oupe";	sons["ouppe"]="oupe";
sons["our"]="our";	sons["ours"]="our";			
sons["ourde"]="ourde";					
sons["ourse"]="ourse";	sons[" ours"]="ourse";				
sons["u"]="u";	sons["ue"]="u";					
sons["uc"]="uc";	sons["uque"]="uc";				
sons["uche"]="uche";					
sons["ucte"]="ucte";					
sons["uisse"]="uisse";					
sons["ule"]="ul";	sons["ulle"]="ul";				
sons["ulbe"]="ulb";					
sons["ulve"]="ulv";					
sons["ume"]="um";					
sons["un"]="un";
sons["une"]="une";
sons["ure"]="ur";	
sons["ute"]="ut"; sons["utte"]="ut";

sons["uce"]="us";	sons["usse"]="us";	sons[" anus"]="us";	sons[" cubitus"]="us";	sons["'anus"]="us";	sons[" plexus"]="us";	
sons[" radius"]="us";	sons[" sinus"]="us";	sons[" cosinus"]="us";
sons[" thalamus"]="us";	sons[" thymus"]="us";	sons[" utérus"]="us";	sons["'utérus"]="us";	sons[" bus"]="us";	
sons[" bonus"]="us";	sons[" malus"]="us";	sons[" virus"]="us";	sons[" angélus"]="us";

sons["uscle"]="uscle";
sons["uste"]="uste";					
					

/////////////////////////////////////////////////////////////////////////////
// les rimes "poil à ..."

poils['a']=[]; poils['a'].push("au bras");
poils["a"].push("aux doigts");
poils["a"].push("à l'estomac");
poils["a"].push("au foie");
poils["a"].push("au plasma");
poils["a"].push("au tibia");
poils["able"]=[]; poils["able"].push("aux lésions inflammables");
poils["able"].push("aux os emboîtables");
poils["ache"]=[]; poils["ache"].push("aux moustaches");
poils["ade"]=[]; poils["ade"].push("à l'arcade");
poils["ade"].push("aux gonades");
poils["afe"]=[]; poils["afe"].push("à la carafe");
poils["age"]=[]; poils["age"].push("aux cartilages");
poils["age"].push("à l'œsophage");
poils["age"].push("au visage");
poils["agme"]=[]; poils["agme"].push("au diaphragme");
poils["aiche"]=[]; poils["aiche"].push("aux verrues pas fraîches");
poils["ail"]=[]; poils["ail"].push("à l'émail");
poils["ail"].push("aux entrailles");
poils["ail"].push("à la taille");
poils["ain"]=[]; poils["ain"].push("au tarin");
poils["ain"].push("au bassin");
poils["ain"].push("au bulbe rachidien");
poils["ain"].push("aux intestins");
poils["ain"].push("aux mains");
poils["ain"].push("aux reins");
poils["ain"].push("aux seins");
poils["ain"].push("au vagin");
poils["ain"].push("aux vaisseaux sanguins");
poils["aine"]=[]; poils["aine"].push("à l'abdomen");
poils["aine"].push("à l'aine");
poils["aine"].push("à la boite crânienne");
poils["aine"].push("à la bedaine");
poils["aine"].push("au cérumen");
poils["aine"].push("à l'hymen");
poils["aine"].push("aux veines");
poils["aire"]=[]; poils["aire"].push("au blaire");
poils["aire"].push("à l'annulaire");
poils["aire"].push("à l'arcade sourcilière");
poils["aire"].push("aux artères");
poils["aire"].push("à l'auriculaire");
poils["aire"].push("à la chair");
poils["aire"].push("aux glaires");
poils["aire"].push("à la jugulaire");
poils["aire"].push("aux lombaires");
poils["aire"].push("aux glandes mammaires");
poils["aire"].push("aux molaires");
poils["aire"].push("aux nerfs");
poils["aire"].push("aux ovaires");
poils["aire"].push("aux paupières");
poils["aire"].push("aux prémolaires");
poils["aire"].push("au sphincter");
poils["aire"].push("à l'uretère");
poils["aire"].push("au derrière");
poils["aise"]=[]; poils["aise"].push("aux mortaises");
poils["aise"].push("au trapèze");
poils["al"]=[]; poils["al"].push("aux amygdales");
poils["al"].push("à l'astragale");
poils["al"].push("à la cavité buccale");
poils["al"].push("au nerf cervical");
poils["al"].push("aux labiales");
poils["al"].push("au cordon ombilical");
poils["al"].push("à la veine temporale");
poils["al"].push("à la colonne vertébrale");
poils["ambe"]=[]; poils["ambe"].push("à l'entrejambe");
poils["ambe"].push("aux jambes");
poils["ambre"]=[]; poils["ambre"].push("aux membres");
poils["ame"]=[]; poils["ame"].push("aux squames");
poils["ampe"]=[]; poils["ampe"].push("aux tempes");
poils["an"]=[]; poils["an"].push("aux dents");
poils["an"].push("au flanc");
poils["an"].push("au gland");
poils["an"].push("aux ligaments");
poils["an"].push("au tympan");
poils["an"].push("au séant");
poils["ance"]=[]; poils["ance"].push("aux protubérances");
poils["anche"]=[]; poils["anche"].push("à la hanche");
poils["ande"]=[]; poils["ande"].push("aux glandes");
poils["ane"]=[]; poils["ane"].push("aux membranes");
poils["ane"].push("aux organes");
poils["âne"]=[]; poils["âne"].push("au crâne");
poils["angue"]=[]; poils["angue"].push("à la langue");
poils["ange"]=[]; poils["ange"].push("aux phalanges");
poils["ante"]=[]; poils["ante"].push("à la verrue purulente");
poils["ante"].push("à la fente");
poils["ante"].push("aux sécrétions effervescentes");
poils["apse"]=[]; poils["apse"].push("aux synapses");
poils["aque"]=[]; poils["aque"].push("au cloaque");
poils["aque"].push("à l'iliaque");
poils["arbe"]=[]; poils["arbe"].push("à la barbe");
poils["arde"]=[]; poils["arde"].push("au myocarde");
poils["arde"].push("à la bedaine rondouillarde");
poils["are"]=[]; poils["are"].push("aux panards");
poils["are"].push("aux glandes sudoripares");
poils["arpe"]=[]; poils["arpe"].push("aux carpes");
poils["arpe"].push("aux métacarpes");
poils["arse"]=[]; poils["arse"].push("aux métatarses");
poils["arse"].push("aux tarses");
poils["as"]=[]; poils["as"].push("à l'atlas");
poils["as"].push("à la face");
poils["as"].push("au pancréas");
poils["asque"]=[]; poils["asque"].push("au corps flasque");
poils["ate"]=[]; poils["ate"].push("aux omoplates");
poils["ate"].push("à la prostate");
poils["ate"].push("à la rate");
poils["aume"]=[]; poils["aume"].push("à la paume");
poils["aude"]=[]; poils["aude"].push("aux fesses chaudes");
poils["aune"]=[]; poils["aune"].push("aux seins en silicone");
poils["aune"].push("aux dents jaunes");
poils["aute"]=[]; poils["aute"].push("aux cotes");
poils["auve"]=[]; poils["auve"].push("aux crâne chauve");
poils["ave"]=[]; poils["ave"].push("dans la bave")
poils["ax"]=[]; poils["ax"].push("au thorax");
poils["é"]=[]; poils["é"].push("aux fessiers");
poils["é"].push("à l'étrier");
poils["é"].push("au gosier");
poils["é"].push("aux mucosités");
poils["é"].push("au nez");
poils["é"].push("au périnée");
poils["é"].push("aux pieds");
poils["é"].push("à la plante des pieds");
poils["é"].push("aux porosités");
poils["é"].push("à la trachée");
poils["é"].push("aux nénés");
poils["é"].push("aux ongles incarnés");
poils["è"]=[]; poils["è"].push("aux bourrelets");
poils["è"].push("au bréchet");
poils["è"].push("au cervelet");
poils["è"].push("au jarret");
poils["è"].push("aux mollets");
poils["è"].push("aux osselets");
poils["è"].push("aux ourlets");
poils["è"].push("au palais");
poils["è"].push("aux poignets");
poils["eau"]=[]; poils["eau"].push("aux abdominaux");
poils["eau"].push("aux canaux lacrymaux");
poils["eau"].push("au marteau");
poils["eau"].push("aux nasaux");
poils["eau"].push("au cerveau");
poils["eau"].push("à la peau");
poils["eau"].push("aux vaisseaux");
poils["èbre"]=[]; poils["èbre"].push("aux vertèbres");
poils["eil"]=[]; poils["eil"].push("aux oreilles");
poils["eil"].push("aux orteils");
poils["elle"]=[]; 
poils["elle"].push("aux aisselles");
poils["elle"].push("à la cervelle");
poils["elle"].push("à la fontanelle");
poils["elle"].push("à l'intestin grêle");
poils["elle"].push("aux mamelles");
poils["elle"].push("à la prunelle");
poils["ème"]=[]; poils["ème"].push("à l'œdème");
poils["entre"]=[]; poils["entre"].push("au ventre");
poils["eps"]=[]; poils["eps"].push("aux biceps");
poils["eps"].push("aux forceps");
poils["eps"].push("aux quadriceps");
poils["eps"].push("au triceps");
poils["èque"]=[]; poils["èque"].push("à la spermathèque");
poils["erge"]=[]; poils["erge"].push("à la verge");
poils["erme"]=[]; poils["erme"].push("au derme");
poils["erme"].push("à l'épiderme");
poils["erte"]=[]; poils["erte"].push("aux plaies ouvertes");
poils["esse"]=[]; poils["esse"].push("aux fesses");
poils["esse"].push("à la graisse");
poils["ète"]=[]; poils["ète"].push("à la tête");
poils["ètre"]=[]; poils["ètre"].push("aux urètres");
poils["ette"]=[]; poils["ette"].push("aux gambettes");
poils["ette"].push("au pet");
poils["ette"].push("aux mirettes");
poils["ette"].push("aux facettes");
poils["ette"].push("aux fossettes");
poils["ette"].push("à la luette");
poils["ette"].push("aux oreillettes");
poils["ette"].push("aux pommettes");
poils["ette"].push("au squelette");
poils["euil"]=[]; poils["euil"].push("à l’œil");
poils["eul"]=[]; poils["eul"].push("à la gueule");
poils["eur"]=[]; poils["eur"].push("au cœur");
poils["eur"].push("au majeur");
poils["eur"].push("au postérieur");
poils["euse"]=[]; poils["euse"].push("aux valseuses");
poils["euse"].push("aux muqueuses");
poils["eux"]=[]; poils["eux"].push("au corps caverneux");
poils["eux"].push("aux cheveux");
poils["eux"].push("à la queue");
poils["eux"].push("aux yeux");
poils["èvre"]=[]; poils["èvre"].push("aux lèvres");
poils["èvre"].push("à la plèvre");
poils["ex"]=[]; poils["ex"].push("au cortex");
poils["ex"].push("à l'index");
poils["ex"].push("au sexe");
poils["i"]=[]; poils["i"].push("au zizi");
poils["i"].push("au kiki");
poils["i"].push("aux sourcils");
poils["ible"]=[]; poils["ible"].push("aux nerfs ultra-sensibles");
poils["ice"]=[]; poils["ice"].push("à l'appendice");
poils["ice"].push("au clitoris");
poils["ice"].push("au coccyx");
poils["ice"].push("à la matrice");
poils["ice"].push("aux orifices");
poils["ice"].push("au pelvis");
poils["ice"].push("au pénis");
poils["ice"].push("au pubis");
poils["ice"].push("à l'éléphantiasis");
poils["iche"]=[]; poils["iche"].push("aux miches");
poils["ide"]=[]; poils["ide"].push("à la carotide");
poils["if"]=[]; poils["if"].push("au pif");
poils["il"]=[]; poils["il"].push("à la bile");
poils["il"].push("aux cils");
poils["il"].push("au nombril");
poils["ille"]=[]; poils["ille"].push("aux chevilles");
poils["ille"].push("aux myofibrilles");
poils["ille"].push("aux papilles");
poils["ille"].push("aux pupilles");
poils["ille"].push("à la synovie");
poils["ille"].push("à la vessie");
poils["imbe"]=[]; poils["imbe"].push("aux limbes");
poils["ime"]=[]; poils["ime"].push("à l'épididyme");
poils["ime"].push("au parenchyme");
poils["ince"]=[]; poils["ince"].push("à la pince");
poils["ine"]=[]; poils["ine"].push("à la boudine");
poils["ine"].push("à l'échine");
poils["ine"].push("aux narines");
poils["ine"].push("à la poitrine");
poils["ine"].push("à la rétine");
poils["ine"].push("aux canines");
poils["inge"]=[]; poils["inge"].push("aux méninges");
poils["inx"]=[]; poils["inx"].push("au larynx");
poils["inx"].push("au pharynx");
poils["inte"]=[]; poils["inte"].push("au verrues plantaires qui chuintent");
poils["inte"].push("à l'orgelet qui suinte");
poils["ip"] = []; poils["ip"].push ("à la lippe");
poils["ip"].push("au slip");
poils["ire"]=[]; poils["ire"].push("à la cire");
poils["ique"]=[]; poils["ique"].push("aux lymphatiques");
poils["ique"].push("au nerf sciatique");
poils["ique"].push("aux zygomatiques");
poils["ise"]=[]; poils["ise"].push("à l'apophyse");
poils["ise"].push("à l'hypophyse");
poils["isque"]=[]; poils["isque"].push("aux disques");
poils["isque"].push("au ménisque");
poils["iste"]=[]; poils["iste"].push("aux cistes");
poils["ite"]=[]; poils["ite"].push("à la bite");
poils["ite"].push("aux orbites");
poils["ite"].push("à la cistite");
poils["ite"].push("à la phlébite");
poils["ive"]=[]; poils["ive"].push("aux gencives");
poils["ive"].push("aux incisives");
poils["o"]=[]; poils["o"].push("aux biscottos");
poils["o"].push("au ciboulot");
poils["o"].push("aux abdos");
poils["o"].push("au dos");
poils["o"].push("aux os");
poils["obe"]=[]; poils["obe"].push("aux lobes");
poils["oque"]=[]; poils["oque"].push("aux staphylocoques");
poils["oque"].push("à ta mère en cloque");
poils["oche"]=[]; poils["oche"].push("à la caboche"); poils["oche"].push("à la galoche");
poils["ode"]=[]; poils["ode"].push("au pseudopode");
poils["ogne"]=[]; poils["ogne"].push("à la trogne");
poils["oïde"]=[]; poils["oïde"].push("aux spermatozoïdes");
poils["oïde"].push("au deltoïde");
poils["oïde"].push("au scaphoïde");
poils["oïde"].push("à la thyroïde");
poils["oile"]=[]; poils["oile"].push("à la moelle");
poils["oin"]=[]; poils["oin"].push("aux poings");
poils["oir"]=[]; poils["oir"].push("à la mâchoire");
poils["oir"].push("aux voies respiratoires");
poils["oitre"]=[]; poils["oitre"].push("au gloitre");
poils["ol"]=[]; poils["ol"].push("aux roubignoles");
poils["ol"].push("aux alvéoles");
poils["ol"].push("aux aréoles");
poils["ol"].push("à l'artériole");
poils["ol"].push("aux auréoles");
poils["ol"].push("aux bronchioles");
poils["ol"].push("au col");
poils["ol"].push("à l'épaule");
poils["ol"].push("aux malléoles");
poils["om"]=[]; poils["om"].push("au duodénum");
poils["om"].push("au jéjunum");
poils["om"].push("au médium");
poils["om"].push("au rectum");
poils["om"].push("au sacrum");
poils["om"].push("au scrotum");
poils["om"].push("au sébum");
poils["om"].push("au septum");
poils["om"].push("au sternum");

poils["ompe"]=[]; poils["ompe"].push("aux trompes");
poils["on"]=[]; poils["on"].push("aux tétons");
poils["on"].push("aux nichons");
poils["on"].push("aux articulations");
poils["on"].push("au bedon");
poils["on"].push("à la circoncision");
poils["on"].push("au colon");
poils["on"].push("au front");
poils["on"].push("aux ganglions");
poils["on"].push("à l'ischion");
poils["on"].push("au limaçon");
poils["on"].push("aux mamelons");
poils["on"].push("au menton");
poils["on"].push("au pavillon");
poils["on"].push("aux poumons");
poils["on"].push("aux rognons");
poils["on"].push("aux secretions");
poils["on"].push("aux talons");
poils["on"].push("aux tendons");
poils["on"].push("à la toison");
poils["on"].push("au tronc");
poils["on"].push("aux végétations");
poils["on"].push("au fion");
poils["once"]=[]; poils["once"].push("aux sourcils qui froncent");
poils["onche"]=[]; poils["onche"].push("à la tronche");
poils["onche"].push("aux bronches");
poils["oncle"]=[]; poils["oncle"].push("au furoncle");
poils["ongle"]=[]; poils["ongle"].push("aux ongles");
poils["onne"]=[]; poils["onne"].push("à la colonne");
poils["ore"]=[]; poils["ore"].push("au corps");
poils["ore"].push("aux pores");
poils["ore"].push("au pylore");
poils["orge"]=[]; poils["orge"].push("à la gorge");
poils["orse"]=[]; poils["orse"].push("au torse");
poils["orte"]=[]; poils["orte"].push("à l'aorte");
poils["os"]=[]; poils["os"].push("à la bosse");
poils["ose"]=[]; poils["ose"].push("à la sclérose");
poils["otte"]=[]; poils["otte"].push("à la calotte");
poils["otte"].push("à la glotte");
poils["ou"]=[]; poils["ou"].push("au cou");
poils["ou"].push("aux genoux");
poils["ou"].push("aux joues");
poils["ou"].push("au trou");
poils["ouce"]=[]; poils["ouce"].push("au pouce");
poils["ouche"]=[]; poils["ouche"].push("à la bouche");
poils["oude"]=[]; poils["oude"].push("au coude");
poils["ouf"]=[]; poils["ouf"].push("à la fouffe");
poils["ouge"]=[]; poils["ouge"].push("aux dents qui bougent");
poils["ouge"].push("aux dents qui bougent");
poils["oui"]=[]; poils["oui"].push("à l’ouïe");
poils["ouille"]=[]; poils["ouille"].push("aux couilles");
poils["oul"]=[]; poils["oul"].push("aux boules");
poils["oul"].push("aux ampoules");
poils["oune"]=[]; poils["oune"].push("à la foufoune");
poils["oupe"]=[]; poils["oupe"].push("à la croupe");
poils["oupe"].push("à la houppe");
poils["our"]=[]; poils["our"].push("aux atours");
poils["ourde"]=[]; poils["ourde"].push("aux esgourdes");
poils["ourse"]=[]; poils["ourse"].push("aux bourses");
poils["u"]=[]; poils["u"].push("au cul");
poils["u"].push("aux tissus");
poils["u"].push("à la poche de pus");
poils["uc"]=[]; poils["uc"].push("à la nuque");
poils["uche"]=[]; poils["uche"].push("aux paluches");
poils["ucte"]=[]; poils["ucte"].push("aux oviductes");
poils["uisse"]=[]; poils["uisse"].push("aux cuisses");
poils["uisse"].push("à l'entrecuisse");
poils["ul"]=[]; poils["ul"].push("aux cellules");
poils["ul"].push("à la clavicule");
poils["ul"].push("à la cuticule");
poils["ul"].push("aux follicules");
poils["ul"].push("aux mandibules");
poils["ul"].push("aux nodules");
poils["ul"].push("aux opercules");
poils["ul"].push("au pédoncule");
poils["ul"].push("aux pellicules");
poils["ul"].push("à la rotule");
poils["ul"].push("aux testicules");
poils["ul"].push("au ventricule");
poils["ul"].push("à la vésicule");
poils["ul"].push("au vestibule");
poils["ul"].push("aux ovules");
poils["ulb"]=[]; poils["ulb"].push("au bulbe");
poils["ulv"]=[]; poils["ulv"].push("à la vulve");
poils["um"]=[]; poils["um"].push("à l'enclume");
poils["un"]=[]; poils["un"].push("importun");
poils["une"]=[]; poils["une"].push("à la verrue innoportune");
poils["ur"]=[]; poils["ur"].push("à la chevelure");
poils["ur"].push("à la commissure");
poils["ur"].push("à la denture");
poils["ur"].push("au fémur");
poils["ur"].push("à la figure");
poils["ur"].push("à la musculature");
poils["ur"].push("à l'ossature");
poils["us"]=[]; poils["us"].push("à l'anus");
poils["us"].push("au cubitus");
poils["us"].push("au mucus");
poils["us"].push("au plexus");
poils["us"].push("au prépuce");
poils["us"].push("au radius");
poils["us"].push("aux sinus");
poils["us"].push("au thalamus");
poils["us"].push("au thymus");
poils["us"].push("à l'utérus");
poils["ut"]=[]; poils["ut"].push("au calbut");
poils["uscle"]=[]; poils["uscle"].push("aux muscles");
poils["uste"]=[]; poils["uste"].push("au buste");
